## 넘파이의 자료형

- 넘파이의 배열 (narray) 클래스는 원소가 모두 같은 자료형이어야 한다.
- array 명령으로 배열을 만들 때 자료형을 명시적으로 적용하려면 dtype 인수를 사용한다.
- 만약 dtype 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추한다. 
- 만들어진 배열의 자료형을 알아내려면 dtype 속성을 보면된다.

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [3]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

- dtype 인수로 지정할 자료형은 다음 표에 보인 것과 같은 'dtype 접두사'로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자수를 의미
- 예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4는 4글자 유니코드 문자열을 뜻한다. 
- 숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.

In [6]:
x = np.array([1,2,3],dtype = 'f')
x.dtype

dtype('float32')

In [7]:
x[0]+x[1]

3.0

In [8]:
x = np.array([1,2,3],dtype = 'U')
x.dtype

dtype('<U1')

In [9]:
x[0] + x[1]

'12'

### Inf와 NaN

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan을 사용할 수 있다. 
- 다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다. 
- 0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [10]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

/var/folders/n_/n7h63p7n0p94s4q0cjjkgtl40000gn/T/ipykernel_2317/1727448928.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
/var/folders/n_/n7h63p7n0p94s4q0cjjkgtl40000gn/T/ipykernel_2317/1727448928.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [11]:
np.log(0)

/var/folders/n_/n7h63p7n0p94s4q0cjjkgtl40000gn/T/ipykernel_2317/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [12]:
np.exp(-np.inf)

0.0

### 배열 생성
- Numpy는 몇가지 단순한 배열을 생성하는 명령을 제공한다.
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace

In [13]:
# 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 명령을 사용한다. 인수로는 배열을 크기를 뜻하는 정수를 넣는다. 
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [14]:
# 크기를 뜻하는 튜플을 입력하면 다차원 배열도 만들 수 있다. 
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# array 명령과 마찬가지로 dtype 인수를 명시하면 해당 자료형 원소를 가진 배열을 만든다.
c = np.zeros((5,2),dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [16]:
# 문자열 배열도 가능하지만 모든 원소의 문자열 크기가 같아야 한다. 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있다. 
d = np.zeros(5, dtype = "U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [17]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [18]:
# 0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다. 
e = np.ones((2,3,4),dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
# 만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다. 
f = np.ones_like(b,dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
# 배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다.
# 이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다. 
# empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.
g = np.empty((4,3))
g

array([[0.00000000e+000, 1.48219694e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.58817677e-052],
       [6.51054616e-091, 3.89111323e-033, 9.98864051e-048],
       [1.39497381e+165, 3.99910963e+252, 1.46030983e-319]])

In [24]:
# arange 명령은 Numpy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.
print(np.arange(10))
print(np.arange(3,21,2)) # 시작, 끝(포함하지 않음), 단계

[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13 15 17 19]


In [26]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
print(np.linspace(0,100,5)) # 시작, 끝(포함), 개수
print(np.logspace(0.1,1,10))

[  0.  25.  50.  75. 100.]
[ 1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171
  5.01187234  6.30957344  7.94328235 10.        ]


### 전치 연산

- 2차원 배열의 전치 연산은 행과 열을 바꾸는 작업이다. 이는 배열의 T 속성으로 구할 수 있다. 
- 메서드가 아닌 속성이라는 점에 유의한다.

In [27]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])